// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv52xxvicL1bzf0VPPA8VzVn3feb-F0W8',
    appId: '1:151163954110:web:b0ee6bfed3c16b597a4fef',
    messagingSenderId: '151163954110',
    projectId: 'your-second-eyes',
    authDomain: 'your-second-eyes.firebaseapp.com',
    storageBucket: 'your-second-eyes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB21Ax7Uw4xJKEuLxsb_CwBCKuWrtnSEWM',
    appId: '1:151163954110:android:4d23591fa999340e7a4fef',
    messagingSenderId: '151163954110',
    projectId: 'your-second-eyes',
    storageBucket: 'your-second-eyes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg7Ml1EjhiQe7JcgTrhPW7CSTzHr5ZuBM',
    appId: '1:151163954110:ios:49918ec3e3f6f1fd7a4fef',
    messagingSenderId: '151163954110',
    projectId: 'your-second-eyes',
    storageBucket: 'your-second-eyes.appspot.com',
    iosClientId: '151163954110-kn8brsml6430r47fomd5okkt287r92dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourSecondEyes',
  );
}
